version: '2'
services:
    web:
        image: chrch/web
        command: python app.py 
        ports:
            - "8000:5000"
        environment:
            ROLE: 'dog'
            DB: 'db'
        networks:
            - petnet
    db:
        image: redis
        networks: 
            - petnet
        
networks:
    petnet:
