version: '2'
services:
    web-dog:
        image: chrch/web
        command: python app.py 
        ports:
            - "8000:5000"
        environment:
            ROLE: 'dog'
            DB: 'db-dog'
        networks:
            - dognet
        labels:
            interlock.hostname: "animals"
            interlock.domain: "dckr.org"
    db-dog:
        image: redis
        networks: 
            - dognet
    web-cat:
        image: chrch/web
        command: python app.py 
        ports:
            - "8001:5000"
        environment:
            ROLE: 'cat'
            DB: 'db-cat'
        networks:
            - catnet
        labels:
            interlock.hostname: "animals"
            interlock.domain: "dckr.org"
    db-cat:
        image: redis
        networks: 
            - catnet
    admin:
        image: markchurch/admin
        command: python /code/app.py 
        networks:
            - dognet
            - catnet
        ports:
            - "8002:5000"
        environment:
            DB1: 'db-dog'
            DB2: 'db-cat'
        
networks:
    catnet:
    dognet:

