version: '3'
services:
    web:
        image: chrch/web:2.0
        deploy:
            mode: replicated
            replicas: 2
            labels:
                com.docker.ucp.mesh.http.5000: "external_route=http://pets.dckr.org,internal_port=5000,sticky_sessions=user"
        ports:
            - 5000
        environment:
            DB: 'db'
        networks:
            - backend
            - ucp-hrm
    
    db:
        image: consul:0.7.2
        command: agent -server -ui -client=0.0.0.0 -bootstrap-expect=3 -retry-join=db -retry-join=db -retry-join=db -retry-interval 5s
        deploy:
            replicas: 3
        ports:
            - 8500:8500 
        environment:
            CONSUL_BIND_INTERFACE: 'eth2'
            CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
        networks: 
            - backend
            
networks:
    backend:
    ucp-hrm:
        external: true
