version: '3'
services:
    web:
        image: chrch/web
        deploy:
            replicas: 1
        ports:
            - 5000
        environment:
            DB: 'db'
        networks:
            - petnet
    
    db:
        image: consul
 #       command: consul agent -data-dir=/tmp/consul -config-file=/run/secrets/consul_encrypt.json
        command: consul agent -data-dir=/tmp/consul -server -bootstrap-expect=3 -retry-join db
        deploy:
            replicas: 3
        networks: 
            - petnet
networks:
    petnet:
